2022-02-15 22:23:24 [DEBUG] 捕获的异常场景为 <class 'TypeError'> (test_yml_fixture.py:54)
2022-02-15 22:23:24 [DEBUG] 捕获的异常场景为 <class 'TypeError'> (test_yml_fixture.py:54)
2022-02-15 22:23:24 [DEBUG] 捕获的异常场景为 <class 'TypeError'> (test_yml_fixture.py:54)
2022-02-15 22:23:24 [DEBUG] 捕获的异常场景为 <class 'TypeError'> (test_yml_fixture.py:54)
2022-02-15 22:23:24 [DEBUG] 捕获的异常场景为 <class 'TypeError'> (test_yml_fixture.py:54)
2022-02-15 22:23:24 [DEBUG] 捕获的异常场景为 <class 'TypeError'> (test_yml_fixture.py:54)
