2022-02-15 22:12:57 [DEBUG] 捕获的异常场景为 <class 'TypeError'> (test_yml_fixture.py:50)
2022-02-15 22:12:57 [DEBUG] 捕获的异常场景为 <class 'TypeError'> (test_yml_fixture.py:50)
